[behave]
features = features
stdout_capture = false
stderr_capture = false
log_capture = false

# Allure formatter
format = allure_behave.formatter:AllureFormatter
outfiles = reports/allure-results

# Show colored output
color = true

# Show skipped steps
show_skipped = true

# Show timing
show_timings = true